FROM golang

ENV GOPATH /code/
ADD . /code/src/github.com/agtorre/gocookbook/chapter11/monitoring
WORKDIR /code/src/github.com/agtorre/gocookbook/chapter11/monitoring
RUN GO111MODULE=on GOPROXY=off go build -mod=vendor

ENTRYPOINT /code/src/github.com/agtorre/gocookbook/chapter11/monitoring/monitoring