FROM golang:1.12.4-alpine3.9

ENV GOPATH /code/
ADD . /code/src/github.com/JngMkk/golang/infra/docker
WORKDIR /code/src/github.com/JngMkk/golang/infra/docker/example
RUN GO111MODULE=on GOPROXY=off go build -mod=vendor

ENTRYPOINT /code/src/github.com/JngMkk/golang/infra/docker/example